"""Persistence port for service accounts."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from jb_orchestrator.security.models import ServiceAccount, ServiceAccountCredential


class ServiceAccountRepository(Protocol):
    async def add(self, account: ServiceAccount) -> None: ...

    async def get(self, account_id: UUID) -> ServiceAccount | None: ...

    async def get_by_key(self, key: str) -> ServiceAccount | None: ...

    async def disable(self, account_id: UUID) -> None: ...


class ServiceAccountCredentialRepository(Protocol):
    async def add(self, credential: ServiceAccountCredential) -> None: ...

    async def get(self, credential_id: UUID) -> ServiceAccountCredential | None: ...

    async def list_for_account(self, account_id: UUID) -> list[ServiceAccountCredential]: ...

    async def revoke(self, credential_id: UUID, revoked_at: datetime) -> None: ...

    async def mark_used(self, credential_id: UUID, used_at: datetime) -> None: ...
